# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('statues', models.IntegerField()),
                ('createtime', models.DateField(auto_now_add=True)),
                ('updatetime', models.DateField(auto_now=True)),
            ],
        ),
    ]
