# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-13 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createtime',
            field=models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatetime',
            field=models.DateField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
