# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-21 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180713_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=32, verbose_name='\u83dc\u5355\u540d')),
                ('url_name', models.CharField(max_length=64, verbose_name='\u5730\u5740\u540d')),
            ],
            options={
                'verbose_name': '\u83dc\u5355\u8868',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=32, unique=True, verbose_name='\u89d2\u8272')),
                ('menus', models.ManyToManyField(blank=True, null=True, to='login.Menu')),
            ],
            options={
                'verbose_name_plural': '\u89d2\u8272\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '\u7528\u6237\u8868'},
        ),
        migrations.AddField(
            model_name='user',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='qq\u53f7'),
        ),
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='statues',
            field=models.BooleanField(choices=[(True, '\u6b63\u5e38\u4f7f\u7528'), (False, '\u505c\u6b62\u4f7f\u7528')], default=True, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='login.Role'),
        ),
    ]
